### ISSUE TITLE
URL needs updating

### ISSUE THREAD

**Issue by CrawfishPress** [joaocarvalhoopen/How_to_learn_modern_Rust#1]
`1. **Why Developers Love Rust** <br>
   [https://ibraheem.ca/posts/why-devs-love-rust/](https://ibraheem.ca/posts/why-devs-love-rust/)
`
*writings* changed to *posts*.

I actually tried to push a PR for this, but couldn't get it working, don't know if it's permissions on your repo, or if I just screwed up. :)

Oh, yeah, excellent resource-list you've created, thanks.

**Comment by joaocarvalhoopen** [comment]
Thank you CrawfishPress, I just made the change.

Best regards,
Joao
