### ISSUE TITLE
how create a clean object?

### ISSUE THREAD

**Issue by xor256** [joaocarvalhoopen/How_to_learn_modern_Rust#4]
How make a .obj or library .a without panic and rust_begin_unwind

**Comment by joaocarvalhoopen** [comment]
Hello, 
The place to ask questions about Rust is:
https://users.rust-lang.org/

There you find a community of great people to answer to all your questions about Rust.
Currently I have no time to answer them.
And there the answer to your question will help others.
Best regards,
