### ISSUE TITLE
[Request] 3D graphics

### ISSUE THREAD

**Issue by SandWoodJones** [joaocarvalhoopen/How_to_learn_modern_Rust#5]
I'm deeply interested in learning 3D graphics in Rust, I just don't have any pointers.

**Comment by joaocarvalhoopen** [comment]
Hello,
Sorry but I didn't explore that path with Rust yet, only with other languages.

see:

Are we game yet?
Almost. We have the blocks, bring your own glue.
https://arewegameyet.rs/

Best regards,
João
